#spring.application.name= DefaultConfig

#eureka.instance.prefer-ip-address= true
#eureka.instance.client.fetch-registry= true
#eureka.instance.client.register-with-eureka= true
#eureka.instance.client.service-url.defaultZone = http://localhost:8761/eureka/

spring:
  application:
    name: DefaultConfig
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
